---
collections:
  - name: update_collection_test.testing_collection
  - name: redhat_cop.ah_configuration

ah_collections:
  - collection_name: debug
    git_url: "https://github.com/otatman/automationhub-collection-test/tree/master/update_collection_test/testing_collection"
ah_auto_approve: true