---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  vars:
    ah_validate_certs: false
    ah_host: "https://10.1.196.109"
  #   ah_token: "26325ad7545104a6d7252c444a036402310a9d8a"
  #  ah_username: "admin"
  #  ah_password: "Pool3ssh!"
  #   ah_path_prefix: "automation-hub"  
  # vars_files:
  #   - var/ah_collections.yml
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var
        extensions: ["yml"]
    # - name: create a directory if it doesnt exist
    #   ansible.builtin.file:
    #     path: "{{ ah_configuration_working_dir }}"
    #     state: directory
    #     mode: '0755'

  tasks:
    
    # - name: authenticate and get an API token
    #   ah_token:
    #     #ah_token: "{{ old_ah_token }}"
    #     state: present
    #     ah_host: "{{ ah_host }}"
    #     ah_username: "{{ ah_username }}"
    #     ah_password: "{{ ah_password }}"
    #     ah_path_prefix: "{{ ah_path_prefix }}"
    #     validate_certs: "{{ ah_validate_certs }}"
        
    - name: publish collections
      include_role: 
        name: publish
      vars:
        ah_auto_approve: true

    # - name: add namespace to AH
    #   include_role:
    #     name: namespace
        

  # roles:
  #   - redhat_cop.ah_configuration.publish
  
  

   
  

    