---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  vars:
    ah_validate_certs: false
  vars_files:
    - /var/ah_configs/ah_auth.yml
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var/ah_configs/
        extensions: ["yml"]

  roles:
    - redhat_cop.ah_configuration.publish
  
  

   
  

    
      